library(shinytest2)

test_that("{shinytest2} recording: top_3_movies_all_time", {
  app <- AppDriver$new(variant = platform_variant(), name = "top_3_movies_all_time", 
      height = 914, width = 1379)
  app$expect_screenshot()
  app$set_inputs(genre_open = TRUE, allow_no_input_binding_ = TRUE)
  app$set_inputs(genre = c("Action", "Adventure", "Animation", "Biography", "Comedy", 
      "Crime", "Drama", "Family", "Fantasy", "Film-Noir", "History", "Horror", "Music", 
      "Musical", "Mystery", "Romance", "Sci-Fi", "Sport", "Thriller", "War", "Western"))
  app$set_inputs(genre_open = FALSE, allow_no_input_binding_ = TRUE)
  app$set_inputs(star_open = TRUE, allow_no_input_binding_ = TRUE)
  app$set_inputs(star = c("Aamir Bashir", "Aamir Khan", "Aaron Eckhart", "Aaron Taylor-Johnson", 
      "Abdel Ahmed Ghili", "Abhay Deol", "Abigail Breslin", "Abraham Attah", "Adam Baldwin", 
      "Adam Driver", "Adel Bencherif", "Adèle Exarchopoulos", "Adèle Haenel", "Adesh Prasad", 
      "Adil Hussain", "Adolphe Menjou", "Adrian Molina", "Adrien Brody", "Agnes Moorehead", 
      "Ahmet Mümtaz Taylan", "Ahna Capri", "Ahney Her", "Aidan Gillen", "Aitana Sánchez-Gijón", 
      "Ajay Devgn", "Ajay Naidu", "Akemi Yamaguchi", "Aki Maeda", "Akihiro Miwa", 
      "Akio Ôtsuka", "Akira Ishihama", "Akira Terao", "Akshay Kumar", "Akshaye Khanna", 
      "Al Ernest Garcia", "Al Pacino", "Alain Delon", "Alakina Mann", "Alan Alda", 
      "Alan Arkin", "Alan Badel", "Alan Mak", "Alan Randolph Scott", "Alan Rickman", 
      "Alan Ruck", "Alan Tudyk", "Albert Brooks", "Albert Finney", "Albert Rémy", 
      "Alberto Ammann", "Aldo Giuffrè", "Aldo Silvani", "Alec Baldwin", "Alec Cawthorne", 
      "Alec Guinness", "Alec Secareanu", "Alejandro Jodorowsky", "Aleksandr Antonov", 
      "Aleksandr Kaydanovskiy", "Aleksey Kravchenko", "Aleksey Rozin", "Aleksey Serebryakov", 
      "Alex Palmer", "Alex Sharp", "Alexander Gould", "Alexander Granach", "Alexandra Maria Lara", 
      "Alexandre Rignault", "Alexandre Rodrigues", "Alexandre Tharaud", "Alexandru Potocean", 
      "Alfred Abel", "Ali Mosaffa", "Alia Bhatt", "Alicia Vikander", "Alida Valli", 
      "Alisa Freyndlikh", "Alison Crosbie", "Alison Doody", "Alison Whelan", "Allen Garfield", 
      "Allen Leech", "Allison Williams", "Ally Sheedy", "Altan Erkekli", "Álvaro Guerrero", 
      "America Ferrera", "Amir Farrokh Hashemian", "Amira Casar", "Amit Sadh", "Amitabh Bachchan", 
      "Amjad Khan", "Amole Gupte", "Amrish Puri", "Amrita Puri", "Amy Adams", "Amy Poehler", 
      "Amy Ryan", "Amy Smart", "Ana de Armas", "Ana López Mercado", "Ana Wagener", 
      "Anamaria Marinca", "Anand Gandhi", "Ananda George", "Anatoliy Solonitsyn", 
      "Andie MacDowell", "André Berley", "André Ramiro", "André S. Labarthe", 
      "Andrea Eckert", "Andrea Riseborough", "Andrea Tariang", "Andreas Wilson", 
      "Andrew Adote", "Andrew Garfield", "Andrew Kevin Walker", "Andrew Marton", 
      "Andrew Philpot", "Andrew Robinson", "Andrew Shim", "Andy Devine", "Andy Garcia", 
      "Andy Lau", "Andy Serkis", "Angela Bassett", "Angela Lansbury", "Angelina Jolie", 
      "Angie Dickinson", "Angus Macfadyen", "Anil Dhawan", "Anita Ekberg", "Anjelica Huston", 
      "Ann Dvorak", "Ann Owens", "Ann Reinking", "Anna Faris", "Anna Foglietta", 
      "Anna Karina", "Anna Kendrick", "Anna Massey", "Annalise Basso", "Anne Bancroft", 
      "Anne Baxter", "Anne Dorval", "Anne Hathaway", "Anne Le Ny", "Anne-Marie Duff", 
      "Annette Bening", "Annie Corley", "Annie Potts", "Annika Wedderkopp", "Annu Kapoor", 
      "Anouk Aimée", "Ansel Elgort", "Ansiba", "Anthony Chau-Sang Wong", "Anthony Edwards", 
      "Anthony Gonzalez", "Anthony Hopkins", "Anthony Michael Hall", "Anthony Perkins", 
      "Anthony Quinn", "Antoine Olivier Pilon", "Anton Walbrook", "Antonella Attili", 
      "Antonia San Juan", "Antonio Banderas", "Antonio Resines", "Anupam Kher", "Anushka Sharma", 
      "Anushka Shetty", "Aoi Miyazaki", "Aoi Yûki", "Aparna Balamurali", "Aras Bulut Iynemli", 
      "Archana Jois", "Ariadna Gil", "Ariane Labed", "Arifin Putra", "Armando Brancia", 
      "Armie Hammer", "Armin Mueller-Stahl", "Arno Frisch", "Arnold Lucy", "Arnold Schwarzenegger", 
      "Arshad Warsi", "Art LaFleur", "Art Malik", "Art Parkinson", "Arthur O'Connell", 
      "Arthur Rosson", "Artyom Bogucharskiy", "Asa Butterfield", "Asaka Seto", "Ash Brannon", 
      "Asha Sharath", "Ashton Kutcher", "Atsuko Tanaka", "Audrey Hepburn", "Audrey Tautou", 
      "Auli'i Cravalho", "Aura Garrido", "Aurélien Recoing", "Aurore Clément", 
      "Aya Okamoto", "Ayami Kakiuchi", "Ayano Shiraishi", "Ayberk Pekcan", "Ayesha Kapoor", 
      "Ayushmann Khurrana", "Azhy Robertson", "Babak Karimi", "Bae Doona", "Bahar Pars", 
      "Bahare Seddiqi", "Bajram Severdzan", "Baki Davrak", "Barbara Bel Geddes", 
      "Barbara Hershey", "Bárbara Lennie", "Barbara Stanwyck", "Baris Bagci", "Barkhad Abdi", 
      "Barkhad Abdirahman", "Barry Bostwick", "Barry Cook", "Barry Fitzgerald", "Barry Humphries", 
      "Barry Keoghan", "Barry Pepper", "Basil Rathbone", "BD Wong", "Beau Billingslea", 
      "Bee Vang", "Belén Rueda", "Ben Affleck", "Ben Burtt", "Ben Foster", "Ben Gazzara", 
      "Ben Hardy", "Ben Johnson", "Ben Kingsley", "Ben Stiller", "Ben Whishaw", "Benedict Cumberbatch", 
      "Bengt Ekerot", "Benicio Del Toro", "Benjamin Bratt", "Benno Fürmann", "Benoît Régent", 
      "Bérénice Bejo", "Bernard-Pierre Donnadieu", "Bernhard Wicki", "Bertil Guve", 
      "Bette Davis", "Beverly D'Angelo", "Bibi Andersson", "Biff McGuire", "Bill Bernstein", 
      "Bill Hader", "Bill McKinney", "Bill Murray", "Bill Nighy", "Bill Nunn", "Bill Paxton", 
      "Bill Pullman", "Bill Sage", "Billy Bob Thornton", "Billy Connolly", "Billy Crudup", 
      "Billy Crystal", "Billy Dee Williams", "Billy Zane", "Birgitta Pettersson", 
      "Birgitta Valberg", "Birol Ünel", "Björk", "Bo Hopkins", "Bob Balaban", "Bob Geldof", 
      "Bob Gunton", "Bob Hoskins", "Bob Odenkirk", "Bob Peterson", "Bobby Cannavale", 
      "Bodil Rosing", "Boluwatife Treasure Bankole", "Boman Irani", "Bonnie Bedelia", 
      "Bonnie Hunt", "Bora Todorovic", "Boris Karloff", "Börje Ahlstedt", "Boyd Holbrook", 
      "Boyd Kirkland", "Brad Davis", "Brad Dourif", "Brad Garrett", "Brad Pitt", 
      "Bradley Cooper", "Bradley Whitford", "Brady Corbet", "Brahim Hadjadj", "Branka Katic", 
      "Branko Djuric", "Brenda Blethyn", "Brenda Fricker", "Brendan Gleeson", "Bria Vinaite", 
      "Brian Cox", "Brian Dennehy", "Brian Howe", "Brian O'Halloran", "Brian Tyler", 
      "Bridget Moynahan", "Brie Larson", "Brigitte Helm", "Brigitte Lin", "Brooke Adams", 
      "Brooklynn Prince", "Bruce Bennett", "Bruce Cabot", "Bruce Campbell", "Bruce Davison", 
      "Bruce Dern", "Bruce Lee", "Bruce Reitherman", "Bruce Spence", "Bruce Willis", 
      "Bruno Ganz", "Bruno Kirby", "Bruno Zanin", "Bryan Cranston", "Bryce Dallas Howard", 
      "Bud Cort", "Buddy Ebsen", "Bulle Ogier", "Bunshi Katsura Vi", "Burak Yigit", 
      "Burl Ives", "Burt Lancaster", "Burt Reynolds", "Burt Young", "Buster Keaton", 
      "Buzz Kilman", "Byron Barr", "Byron Howard", "Cab Calloway", "Caio Junqueira", 
      "Caitriona Balfe", "Caleb Landry Jones", "Callan McAuliffe", "Cameron Diaz", 
      "Candela Peña", "Carey Mulligan", "Carice van Houten", "Carl Benton Reid", 
      "Carl Miller", "Carl Möhner", "Carl Weathers", "Carla Gugino", "Carla Quevedo", 
      "Carlo Buccirosso", "Carlo Verdone", "Carlos Martínez López", "Carlos Peralta", 
      "Carol Kane", "Carole Lombard", "Caroline Goodall", "Carrie Fisher", "Carrie Henn", 
      "Carrie-Anne Moss", "Carroll Baker", "Carroll O'Connor", "Cary Elwes", "Cary Grant", 
      "Cary-Hiroyuki Tagawa", "Casey Affleck", "Cate Blanchett", "Catherine Deneuve", 
      "Catherine Keener", "Catherine O'Hara", "Cathy Moriarty", "Cathy Rosier", "Catinca Untaru", 
      "Cecil Parker", "Cecilia Roth", "Celeste Holm", "Celia Johnson", "Celile Toyon Uysal", 
      "Cem Yilmaz", "Çetin Tekindor", "Charles Bronson", "Charles Chaplin", "Charles Durning", 
      "Charles Fleischer", "Charles Laughton", "Charles Martin Smith", "Charles Ruggles", 
      "Charles Vanel", "Charley Grapewin", "Charlie Cox", "Charlie Hunnam", "Charlie Pye Jr.", 
      "Charlie Sheen", "Charlie Yeung", "Charlize Theron", "Charlotte Rampling", 
      "Charlton Heston", "Chase Ellison", "Chazz Palminteri", "Chen Chang", "Chete Lera", 
      "Chiara Mastroianni", "Chico Marx", "Chief Dan George", "Chieko Baishô", "Chieko Higashiyama", 
      "Chika Sakamoto", "Chishû Ryû", "Chiwetel Ejiofor", "Chloë Grace Moretz", 
      "Cho Jin-woong", "Cho Yeo-jeong", "Choi Min-sik", "Choi Woo-sik", "Chris Cooper", 
      "Chris Elliott", "Chris Evans", "Chris Hemsworth", "Chris O'Donnell", "Chris Owen", 
      "Chris Penn", "Chris Pine", "Chris Pratt", "Chris Renaud", "Chris Sanders", 
      "Chris Sarandon", "Chris Williams", "Christian Bale", "Christian Berkel", "Christian Friedel", 
      "Christian Slater", "Christina Hendricks", "Christine Hargreaves", "Christoph Waltz", 
      "Christopher Adamson", "Christopher Carley", "Christopher Eccleston", "Christopher Guest", 
      "Christopher Heyerdahl", "Christopher Lloyd", "Christopher Mintz-Plasse", "Christopher Plummer", 
      "Christopher Reeve", "Christopher Rivera", "Christopher Walken", "Chulpan Khamatova", 
      "Ciarán Hinds", "Cillian Murphy", "Claire Bloom", "Claire Danes", "Claire Maurier", 
      "Claire Rushbrook", "Claire Trevor", "Clark Gable", "Claude Rains", "Claudette Colbert", 
      "Claudia Cardinale", "Cleavon Little", "Clifton Powell", "Clifton Webb", "Clint Eastwood", 
      "Clive Owen", "Coleen Gray", "Colin Clive", "Colin Farrell", "Colin Firth", 
      "Colm Feore", "Connie Nielsen", "Conrad Veidt", "Corey Feldman", "Corey Hawkins", 
      "Cori Gonzalez-Macuer", "Craig Bierko", "Craig Ferguson", "Craig Parkinson", 
      "Craig T. Nelson", "Crispin Glover", "Cuba Gooding Jr.", "Cuifen Cao", "Curt Bois", 
      "Cybill Shepherd", "Cyril Cusack", "Dafne Keen", "Daisuke Ryû", "Daisy Ridley", 
      "Dakota Fanning", "Dakota Johnson", "Dalia Hernández", "Damian Chapa", "Dan Aykroyd", 
      "Dan Hedaya", "Dan Hicks", "Dan Riba", "Dana Andrews", "Dana Wynter", "Danai Gurira", 
      "Daniel Boulanger", "Daniel Brühl", "Daniel Craig", "Daniel Day-Lewis", "Daniel Giménez Cacho", 
      "Daniel Kaluuya", "Daniel Mays", "Daniel Prévost", "Daniel Radcliffe", "Daniel Richter", 
      "Daniel Stern", "Danielle Proulx", "Danny Aiello", "Danny Denzongpa", "Danny Elfman", 
      "Danny Glover", "Danny Huston", "Danny Lee", "Danny Lloyd", "Dara Singh", "Darío Grandinetti", 
      "Darren McGavin", "Darryl F. Zanuck", "Darsheel Safary", "Daryl Hannah", "Dave Bautista", 
      "Dave Goelz", "Dave Johns", "Daveigh Chase", "David Carradine", "David Della Rocco", 
      "David Emge", "David Hand", "David Hemmings", "David Herman", "David James", 
      "David Lee Smith", "David Morse", "David Rawle", "David Silverman", "David Thewlis", 
      "David Tomlinson", "David Wenham", "David Zucker", "Davor Dujmovic", "Dean Martin", 
      "Dean Stockwell", "Dean-Charles Chapman", "Debbie Reynolds", "Deborah Kara Unger", 
      "Deborah Kerr", "Debra Messing", "Dee Wallace", "DeForest Kelley", "Del Negro", 
      "Delphine Seyrig", "Delroy Lindo", "Demet Akbag", "Demi Moore", "Denholm Elliott", 
      "Deniz Baysal", "Dennis Farina", "Dennis Hopper", "Dennis Price", "Dennis Quaid", 
      "Denzel Washington", "Derek Jacobi", "Dev Patel", "Dexter Fletcher", "Dharmendra", 
      "Diahnne Abbott", "Diane Keaton", "Diane Kruger", "Diane Ladd", "Diane Venora", 
      "Dianne Wiest", "Dibyendu Bhattacharya", "Dick Hogan", "Dick Van Dyke", "Dick York", 
      "Diego Cortina Autrey", "Diego Luna", "Diego Starosta", "Diljit Dosanjh", "Disha Patani", 
      "Dita Parlo", "Djimon Hounsou", "Doga Zeynep Doguslu", "Dolly Ahluwalia", "Dolores Moran", 
      "Domhnall Gleeson", "Dominic West", "Dominique Blanchar", "Dominique McElligott", 
      "Dominique Pinon", "Don Cheadle", "Don Gordon", "Don Hall", "Don Rickles", 
      "Don Taylor", "Donald O'Connor", "Donald Pleasence", "Donald Sutherland", "Donatas Banionis", 
      "Donna Murphy", "Donna Reed", "Donnie Yen", "Donny Alamsyah", "Dorian Gray", 
      "Dorothy Comingore", "Dorothy Duffy", "Dorsey Wright", "Doug McKeon", "Douglas Booth", 
      "Drew Barrymore", "Duane Jones", "Dustin Hoffman", "Dwight Yoakam", "Dylan Baker", 
      "Ed Harris", "Ed Helms", "Ed Skrein", "Eddie Albert", "Eddie Murphy", "Eddie Redmayne", 
      "Edgar Ramírez", "Edmond O'Brien", "Edmund Goulding", "Edmund Gwenn", "Edna Purviance", 
      "Edoardo Leo", "Eduard Abalov", "Eduardo Noriega", "Edward Arnold", "Edward Asner", 
      "Edward Burns", "Edward Fox", "Edward Furlong", "Edward G. Robinson", "Edward James Olmos", 
      "Edward Norton", "Efrem Zimbalist Jr.", "Ege Tanman", "Eiji Okada", "Eijirô Tôno", 
      "Eiko Masuyama", "Eileen Walsh", "Eiza González", "Eleanor Bron", "Eleanor David", 
      "Eleanor Parker", "Elena Altieri", "Elena Anaya", "Elena Lyadova", "Eli Marienthal", 
      "Eli Roth", "Eli Wallach", "Elijah Smith", "Elijah Wood", "Elisabeth Shue", 
      "Elissa Knight", "Elit Iscan", "Eliza Scanlen", "Elizabeth Banks", "Elizabeth Berridge", 
      "Elizabeth Berrington", "Elizabeth McGovern", "Elizabeth Taylor", "Ellar Coltrane", 
      "Ellen Burstyn", "Ellen Crawford", "Ellen DeGeneres", "Ellen Widmann", "Elliot Page", 
      "Elliott Gould", "Elmo Nüganen", "Elpidia Carrillo", "Elsa Lanchester", "Elya Baskin", 
      "Emeric Pressburger", "Emi Shinohara", "Emile Hirsch", "Émile Vallée", "Emilia Fox", 
      "Emilio Echevarría", "Emilio Estevez", "Emily Blunt", "Emily Mortimer", "Emily Watson", 
      "Emma Stone", "Emma Thompson", "Emma Watson", "Emmanuel Affadzi", "Emmanuelle Riva", 
      "Emmanuelle Seigner", "Emmy Rossum", "Enrique Castillo", "Enrique Rambal", 
      "Enzo Cannavale", "Enzo Staiola", "Enzo Tarascio", "Erdem Can", "Eric Bana", 
      "Eric Baugin", "Eric Idle", "Eric Radomski", "Eric Schweig", "Eric Sykes", 
      "Éric Toledano", "Erich von Stroheim", "Ernest B. Schoedsack", "Ernest Borgnine", 
      "Ernst Jacobi", "Errol Flynn", "Erwin Connelly", "Ethan Coen", "Ethan Hawke", 
      "Eugene Silvain", "Eun-ju Lee", "Eva Green", "Eva Marie Saint", "Evan McGuire", 
      "Evan Rachel Wood", "Evgeniy Zharikov", "Ewa Fröling", "Ewan McGregor", "Ewen Bremner", 
      "Ezra Miller", "F. Murray Abraham", "Famke Janssen", "Farhan Akhtar", "Farida Jalal", 
      "Farley Granger", "Fatima Sana Shaikh", "Fay Wray", "Faye Dunaway", "Faye Wong", 
      "Fele Martínez", "Felicity Jones", "Felix Bressart", "Fengyi Zhang", "Ferdia Walsh-Peelo", 
      "Fernanda Montenegro", "Fernando Rey", "Fikret Kuskan", "Filip Berg", "Filip Sovagovic", 
      "Filipp Yankovskiy", "Fionn Whitehead", "Fionnula Flanagan", "Florence Lee", 
      "Florence Pugh", "Florian Lukas", "Florijan Ajdini", "Folco Lulli", "Ford Beebe Jr.", 
      "Forest Whitaker", "Franca Marzi", "Frances Conroy", "Frances McDormand", "Frances Sternhagen", 
      "Francine Racette", "Francis Capra", "Francis Huster", "François Berléand", 
      "François Cluzet", "François Périer", "François Truffaut", "Frank Adu", 
      "Frank Finlay", "Frank Giering", "Frank Langella", "Frank Lovejoy", "Frank Morgan", 
      "Frank Overton", "Frank Oz", "Frank Paur", "Frank Sinatra", "Frank Vincent", 
      "Franka Potente", "Frantz Turner", "Franz Rogowski", "Fred MacMurray", "Fred Willard", 
      "Frederic Forrest", "Frederick Lau", "Frédérique Feder", "Fredric March", 
      "Freida Pinto", "Friedrich Feher", "Gabriel Byrne", "Gabriele Ferzetti", "Gabrielle Anwar", 
      "Gael García Bernal", "Gajraj Rao", "Garrett M. Brown", "Gary Busey", "Gary Cooper", 
      "Gary Farmer", "Gary Lockwood", "Gary Oldman", "Gary Sinise", "Gary Stretch", 
      "Gaspard Manesse", "Gaspard Ulliel", "Gastón Pauls", "Gastone Moschin", "Gattlin Griffith", 
      "Gayatri Joshi", "Gaylen Ross", "Geert Van Rampelberg", "Gemma Jones", "Gena Rowlands", 
      "Gene Bervoets", "Gene Hackman", "Gene Kelly", "Gene Lockhart", "Gene Tierney", 
      "Gene Wilder", "Geneviève Page", "Geoffrey Arend", "Geoffrey Rush", "George C. Scott", 
      "George Clooney", "George Cukor", "George Harrison", "George Kennedy", "George MacKay", 
      "George Macready", "George O'Brien", "George Peppard", "George Raft", "George Sanders", 
      "George Segal", "Georges Adet", "Georges Siatidis", "Gerald R. Molen", "Geraldine Chaplin", 
      "Gerard Butler", "Gerard Hendrick", "Gérard Jugnot", "Gerardo Taracena", "Gerd Oswald", 
      "Gerry Robert Byrne", "Gert Fröbe", "Gian Maria Volontè", "Gil Birmingham", 
      "Gillian Anderson", "Gina Torres", "Ginnifer Goodwin", "Giorgi Nakashidze", 
      "Giorgio Cantarini", "Giovanni Ribisi", "Giulietta Masina", "Giuseppe Battiston", 
      "Giustino Durano", "Gladys George", "Glen Cavender", "Glen Hansard", "Glenn Ford", 
      "Gloria Grahame", "Gloria Stuart", "Gloria Swanson", "Glynis Johns", "Godfrey Tearle", 
      "Golshifteh Farahani", "Gong Li", "Gore Vidal", "Gorô Naya", "Goya Toledo", 
      "Grace Kelly", "Graciela Tenenbaum", "Gracy Singh", "Graham Chapman", "Graham Greene", 
      "Graham Norton", "Greg Cruttwell", "Greg Grunberg", "Greg Kinnear", "Gregory Peck", 
      "Greta Schröder", "Griffin Dunne", "Grigoriy Aleksandrov", "Groucho Marx", 
      "Guillaume Canet", "Günes Sensoy", "Gunnar Björnstrand", "Gunnel Lindblom", 
      "Gustaf Skarsgård", "Gustav Fröhlich", "Gustav von Wangenheim", "Güven Kiraç", 
      "Guy Decomble", "Guy Pearce", "Guylaine Schlumberger", "Gwen Eckhaus", "Gwilym Lee", 
      "Gwyneth Paltrow", "Haaz Sleiman", "Hailee Steinfeld", "Haing S. Ngor", "Haley Joel Osment", 
      "Halina Gryglaszewska", "Halina Reijn", "Haluk Bilginer", "Halvar Björk", 
      "Hanno Pöschl", "Hardy Krüger", "Harold Ramis", "Harpo Marx", "Harriet Andersson", 
      "Harrison Ford", "Harry Connick Jr.", "Harry Crocker", "Harry Dean Stanton", 
      "Harry Guardino", "Harry Myers", "Harshaali Malhotra", "Hartley Power", "Haru Kuroki", 
      "Haruo Tanaka", "Harvey Keitel", "Harvey Korman", "Haya Harareet", "Hayley Squires", 
      "Heath Ledger", "Hector Elizondo", "Hee Jae", "Hee-won Kim", "Helen Hunt", 
      "Helena Bonham Carter", "Helena Rojo", "Helmut Griem", "Helmut Qualtinger", 
      "Hemendra Dandotiya", "Henning Moritzen", "Henri Serre", "Henri-Jacques Huet", 
      "Henrik Dahl", "Henrik Lundström", "Henry Bergman", "Henry Cavill", "Henry Fonda", 
      "Henry Thomas", "Henry Travers", "Herb Edelman", "Herbert Grönemeyer", "Herbert Knaup", 
      "Herbert Lom", "Hiam Abbass", "Hideaki Anno", "Hidetoshi Nishijima", "Hilary Swank", 
      "Hiromasa Yonebayashi", "Hiroyuki Okiura", "Hisako Kyôda", "Hitoshi Takagi", 
      "Ho-jin Chun", "Holly Hunter", "Holmes Osborne", "Honor Blackman", "Horacio Salinas", 
      "Howard Da Silva", "Hrithik Roshan", "Hubert Koundé", "Hubertus Bengsch", 
      "Huck Milner", "Hudhail Al-Amir", "Hugh Bonneville", "Hugh Grant", "Hugh Jackman", 
      "Hugh Marlowe", "Hugh Walsh", "Hugh Welchman", "Hugo Silva", "Hugo Weaving", 
      "Hümeyra", "Humphrey Bogart", "Husnija Hasimovic", "Hye-ja Kim", "Hyeong-jin Kong", 
      "Hyuk-ho Kwon", "Iain Rea", "Ian Hart", "Ian Hendry", "Ian Holm", "Ian McKellen", 
      "Ida Engvoll", "Iemasa Kayumi", "Ignat Daniltsev", "Iko Uwais", "Ileana D'Cruz", 
      "Ilker Kizmaz", "Imelda Staunton", "In-mun Kim", "Indraneil Sengupta", "Inge Landgut", 
      "Ingrid Bergman", "Ingrid Thulin", "Irandhir Santos", "Irène Jacob", "Irene Miracle", 
      "Irene Papas", "Irrfan Khan", "Irving Metzman", "Isa Danieli", "Isaac Hayes", 
      "Isabella Rossellini", "Isabelle Adjani", "Isabelle Huppert", "Ismail Hacioglu", 
      "Issey Takahashi", "Isuzu Yamada", "Ivan Bobrov", "Ivan Dobronravov", "Ivan Lapikov", 
      "Ivana Baquero", "Izabela Vidovic", "J. Mackye Gruber", "J.D. Cannon", "J.K. Simmons", 
      "J.T. Walsh", "Jack Albertson", "Jack Benny", "Jack Carson", "Jack Hawkins", 
      "Jack Kehoe", "Jack Lemmon", "Jack McBrayer", "Jack Nicholson", "Jack Oakie", 
      "Jack Reynor", "Jack Thibeau", "Jack Warden", "Jacki Weaver", "Jackie Coogan", 
      "Jackie Earle Haley", "Jackie Gleason", "Jacob Tremblay", "Jacqueline Andere", 
      "Jacques Villeret", "Jaden Smith", "Jae Head", "Jae-ho Song", "Jake Gyllenhaal", 
      "Jake Johnson", "James Booth", "James Caan", "James Cagney", "James Coburn", 
      "James Cromwell", "James Dean", "James Doohan", "James Earl Jones", "James Fleet", 
      "James Garner", "James Gleason", "James Laurenson", "James Marsden", "James Mason", 
      "James McAvoy", "James Rebhorn", "James Remar", "James Stewart", "James Woods", 
      "Jamie Bell", "Jamie Chung", "Jamie Draven", "Jamie Foxx", "Jamie Lee Curtis", 
      "Jan Cornet", "Jan Josef Liefers", "Jan Pinkava", "Jan Sterling", "Jane Adams", 
      "Jane Alexander", "Jane Darwell", "Jane Fonda", "Jane Galloway Heitz", "Jane Greer", 
      "Jane Lynch", "Jane Wyman", "Janelle Monáe", "Janet Gaynor", "Janet Leigh", 
      "Jang Dong-Gun", "Janine Darcey", "Janusz Gajos", "Jared Bush", "Jared Gilman", 
      "Jared Leto", "Jason Bateman", "Jason Cope", "Jason Flemyng", "Jason Lee", 
      "Jason London", "Jason Mitchell", "Jason Patric", "Jason Robards", "Jason Schwartzman", 
      "Jason Segel", "Jason Statham", "Javier Bardem", "Javier Cámara", "Jay Baruchel", 
      "Jay C. Flippen", "Jaya Bachchan", "JB Blanc", "Je-mun Yun", "Jean Arthur", 
      "Jean Dujardin", "Jean Gabin", "Jean Heywood", "Jean Martin", "Jean Reno", 
      "Jean Seberg", "Jean Servais", "Jean Simmons", "Jean Sorel", "Jean Topart", 
      "Jean-Baptiste Maunier", "Jean-Claude Donda", "Jean-Louis Trintignant", "Jean-Marc Barr", 
      "Jean-Paul Belmondo", "Jean-Pierre Jeunet", "Jean-Pierre Léaud", "Jean-Pierre Lorit", 
      "Jeanne Bates", "Jeanne Moreau", "Jeff Anderson", "Jeff Bridges", "Jeff Cohen", 
      "Jeff Daniels", "Jeff Garlin", "Jeff Goldblum", "Jeffrey Ho", "Jeffrey Hunter", 
      "Jeffrey Jones", "Jeffrey Wright", "Jemaine Clement", "Jena Malone", "Jennifer Aniston", 
      "Jennifer Connelly", "Jennifer Drake", "Jennifer Garner", "Jennifer Jason Leigh", 
      "Jennifer Lawrence", "Jennifer Lien", "Jennifer Morrison", "Jennifer Saunders", 
      "Jennifer Ulrich", "Jeon Gook-Hwan", "Jeremy Irons", "Jeremy Renner", "Jeremy Strong", 
      "Jerome Flynn", "Jerry Lewis", "Jerry Nelson", "Jerry O'Connell", "Jerry Zucker", 
      "Jerzy Stuhr", "Jesse Borrego", "Jesse Corti", "Jesse Eisenberg", "Jessica Biel", 
      "Jessica Chastain", "Jessica Lange", "Jessica Tandy", "Jessie Royce Landis", 
      "Jet Li", "Ji-Eun Lim", "Jim Backus", "Jim Carrey", "Jim Caviezel", "Jim Henson", 
      "Jim Kelly", "Jim Sturgess", "Jim Varney", "Jimmy Sheirgill", "Jin Goo", "Jin-mo Joo", 
      "Jingwu Ma", "Jinpachi Nezu", "Jo Hartley", "Jo Van Fleet", "Joan Allen", "Joan Chen", 
      "Joan Crawford", "Joan Cusack", "Joan Fontaine", "Joan Greenwood", "Joanna Cassidy", 
      "Joanne Dru", "Joaquin Phoenix", "Jodi Benson", "Jodie Foster", "Joe Keaton", 
      "Joe Pantoliano", "Joe Pesci", "Joe Russo", "Joel Basman", "Joel Coen", "Joel Edgerton", 
      "Joel Grey", "Johan Heldenbergh", "Johanna ter Steege", "John Belushi", "John Billingsley", 
      "John Boles", "John Boyega", "John Buckwalter", "John C. Reilly", "John Cameron Mitchell", 
      "John Candy", "John Carradine", "John Cassavetes", "John Castle", "John Cazale", 
      "John Cho", "John Cleese", "John Cusack", "John Dall", "John Fiedler", "John Fraser", 
      "John Gallagher Jr.", "John Gavin", "John Getz", "John Gielgud", "John Goodman", 
      "John Haycraft", "John Heard", "John Hillerman", "John Hodgman", "John Hodiak", 
      "John Hubley", "John Hurt", "John Huston", "John Leguizamo", "John Lennon", 
      "John Lone", "John Lurie", "John Mahoney", "John Malkovich", "John Matthews", 
      "John McGiver", "John Megna", "John Musker", "John Payne", "John Rafter Lee", 
      "John Randolph", "John Ratzenberger", "John Rhys-Davies", "John Ridgely", "John Ritter", 
      "John Roselius", "John Savage", "John Saxon", "John Sharian", "John Travolta", 
      "John Turturro", "John Wayne", "John Williams", "John Wray", "Johnny Depp", 
      "Johnny Sekka", "Jon Bernthal", "Jon Hamm", "Jon Lovitz", "Jon Voight", "Jonah Hill", 
      "Jonathan Pryce", "Jonathan Rhys Meyers", "Jong-ho Kim", "Jonny Lee Miller", 
      "Jordan Nagai", "José Baviera", "Jose Coronado", "José Lewgoy", "Josef Altin", 
      "Joseph A. Carpenter", "Joseph Calleia", "Joseph Cotten", "Joseph Fiennes", 
      "Joseph Gordon-Levitt", "Joseph Lee", "Joseph Melito", "Joseph Schildkraut", 
      "Joséphine Lebas-Joly", "Josh Brolin", "Josh Charles", "Josh Hartnett", "Josh Lucas", 
      "Josh O'Connor", "Joyce Carey", "Juan Ferrara", "Judd Hirsch", "Judd Nelson", 
      "Jude Law", "Judi Dench", "Judith Anderson", "Judith O'Dea", "Judy Davis", 
      "Julia Greer", "Julia Jones", "Julia Ormond", "Julia Roberts", "Julia Stiles", 
      "Julian Arahanga", "Julian Dennison", "Julian Sands", "Juliane Köhler", "Julianne Moore", 
      "Julianne Nicholson", "Julie Andrews", "Julie Christie", "Julie Delpy", "Julie Hagerty", 
      "Julie Harris", "Julie Kavner", "Julie Walters", "Juliette Binoche", "Juliette Lewis", 
      "Juliette Mayniel", "Jun Ji-Hyun", "June Squibb", "Jung-woo Ha", "Junko Iwao", 
      "Jürgen Prochnow", "Jürgen Vogel", "Jüri Järvet", "Justin Bartha", "Justin Braine", 
      "Justin Henry", "Justin Theroux", "Justin Timberlake", "Justine Waddell", "Jyoti Malshe", 
      "Ka Tung Lam", "Kad Merad", "Kagiso Kuypers", "Kaitlyn Dever", "Kajol", "Kalina Jedrusik", 
      "Kalki Koechlin", "Kamatari Fujiwara", "Kang Hye-jeong", "Kang-ho Song", "Kangana Ranaut", 
      "Kappei Yamaguchi", "Kara Hayward", "Kåre Hedebrant", "Kareena Kapoor", "Karen Allen", 
      "Karen Morley", "Kari Sylwan", "Karina Arroyave", "Karisma Kapoor", "Karl Hardman", 
      "Karl Malden", "Karlheinz Böhm", "Kasi Lemmons", "Kassie Wesley DePaiva", 
      "Kasumi Arimura", "Kate Ashfield", "Kate Hudson", "Kate Mara", "Kate Winslet", 
      "Katharine Hepburn", "Katharine Houghton", "Katharine Ross", "Katherine Helmond", 
      "Kathryn McGuire", "Kathy Bates", "Kátia Lund", "Katie A. Keane", "Katrin Cartlidge", 
      "Katrin Saß", "Katrina Kaif", "Katsunosuke Hori", "Kawsar Al Haddad", "Kay Kay Menon", 
      "Kayoko Kishimoto", "Kazuko Yoshiyuki", "Kazunari Ninomiya", "Kazuya Tsurumaki", 
      "Keanu Reeves", "Keenan Wynn", "Keiju Kobayashi", "Keiko Tsushima", "Keiko Yokozawa", 
      "Keir Dullea", "Keira Knightley", "Keith David", "Kelsey Asbille", "Kemp Powers", 
      "Ken Foree", "Ken Leung", "Ken Stott", "Ken Watanabe", "Ken'ichi Hagiwara", 
      "Ken'ichi Matsuyama", "Kenneth Branagh", "Kenshô Ono", "Keri Russell", "Kermit the Frog", 
      "Kerry Washington", "Kevin Bacon", "Kevin Costner", "Kevin Jarre", "Kevin McCarthy", 
      "Kevin McKidd", "Kevin Peter Hall", "Kevin Spacey", "Ki-duk Kim", "Kiara Advani", 
      "Kiefer Sutherland", "Kim Basinger", "Kim Byeong-Ok", "Kim Greist", "Kim Hunter", 
      "Kim Min-hee", "Kim Novak", "Kim Sang-kyung", "Kim Tae-Woo", "Kim Uylenbroek", 
      "Kim Yoon-seok", "Kim Young-Min", "Kimberly Stringer", "King Donovan", "Kirin Kiki", 
      "Kirk Acevedo", "Kirk Douglas", "Kirk Wise", "Kirron Kher", "Kirsten Dunst", 
      "Kirsten Sheridan", "Kirti Kulhari", "Kishori Ballal", "Kiyoshi Kobayashi", 
      "Klaus Kinski", "Klaus Wennemann", "Kodi Smit-McPhee", "Kôichi Yamadera", 
      "Kong Chu", "Konkona Sen Sharma", "Konstantin Lavronenko", "Kotoe Hatsui", 
      "Koyu Rankin", "Kristen Wiig", "Kristina Adolphson", "Kumud Mishra", "Kurt Fuller", 
      "Kurt Russell", "Kyle Chandler", "Kyle MacLachlan", "Kyôko Kagawa", "Kyung-jin Lee", 
      "Lady Gaga", "Laia Costa", "Laila Robins", "Lamberto Maggiorani", "Lance Henriksen", 
      "Lari White", "Larry Gates", "Lars Ranthe", "Lasse Fogelstrøm", "Laura Dern", 
      "Laura Harring", "Laura Linney", "Laura Obiols", "Laura Vasiliu", "Lauren Bacall", 
      "Lauren Ridloff", "Laurence Fishburne", "Laurence Harvey", "Laurence Olivier", 
      "Lawrence A. Bonney", "Lazar Ristovski", "Lea Massari", "Léa Seydoux", "Lea Thompson", 
      "Leandro Firmino", "Lee Byung-Hun", "Lee Grant", "Lee J. Cobb", "Lee Marvin", 
      "Lee Pace", "Lee Remick", "Lee Sun-kyun", "Lee Unkrich", "Lee Van Cleef", "Lee Yeong-ae", 
      "Leigh Whannell", "Leila Hatami", "Leila Hyams", "Leland Orser", "Leland Palmer", 
      "Lembit Ulfsak", "Lena Endre", "Lena Headey", "Lena Nyman", "Leo G. Carroll", 
      "Leo McKern", "Leon Lai", "Leonard Frey", "Leonard Nimoy", "Leonardo DiCaprio", 
      "Leonie Benesch", "Leonor Watling", "Lesley Sharp", "Leslie Cheung", "Leslie Nielsen", 
      "Leslie Odom Jr.", "Lew Ayres", "Lewis Black", "Li Sun", "Liam Aiken", "Liam Cunningham", 
      "Liam Neeson", "Lianella Carell", "Liesel Matthews", "Liev Schreiber", "Lil Dagover", 
      "Lillete Dubey", "Lillian Gish", "Lillo Brancato", "Lilly Wachowski", "Lily Franky", 
      "Lin-Manuel Miranda", "Lina Leandersson", "Linda Blair", "Linda Cardellini", 
      "Linda Hamilton", "Linda Larkin", "Linda Manz", "Linda Zilliacus", "Lindsay Duncan", 
      "Linh Dan Pham", "Lionel Barrymore", "Lisa Hannigan", "Lisa Haydon", "Lisa Spoonauer", 
      "Lisanne Falk", "Liubomiras Laucevicius", "Liv Ullmann", "Liza Minnelli", "Ljubica Adzovic", 
      "Lloyd Avery II", "Lloyd Bridges", "Logan Lerman", "Lola Dueñas", "Lorelei Linklater", 
      "Lorella Cravotta", "Lori Martin", "Lorraine Bracco", "Lorraine Gary", "Lou Romano", 
      "Louis Calhern", "Louis Eppolito", "Louis Hofmann", "Louis Prima", "Louis Wolheim", 
      "Louise Fletcher", "Louise Lemoine Torrès", "Loveleen Tandan", "Luàna Bajrami", 
      "Lubna Azabal", "Lucas Hedges", "Lucie Mannheim", "Lucy Boynton", "Lucy Davis", 
      "Lucy Liu", "Luis Guzmán", "Luis Tosar", "Luke Bracey", "Lydia Wilson", "Lyubov Agapova", 
      "Mabel Rivera", "Macaulay Culkin", "Macdonald Carey", "Machiko Kyô", "Mack Swain", 
      "Mackenzie Foy", "Madeleine Carroll", "Madeleine Stowe", "Madeline Carroll", 
      "Madeline Kahn", "Madhavan", "Mads Mikkelsen", "Mae Clarke", "Magali Noël", 
      "Maggie Cheung", "Maggie Grace", "Maggie Smith", "Magnus Millang", "Mahershala Ali", 
      "Mahesh Manjrekar", "Mahie Gill", "Mahito Tsujimura", "Makio Inoue", "Malcolm McDowell", 
      "Malin Akerman", "Mamaengaroa Kerr-Bell", "Mami Koyama", "Mandy Moore", "Mandy Patinkin", 
      "Manjot Singh", "Manoj Bajpayee", "Manuel Morón", "Mara Krupp", "Marc-André Grondin", 
      "Marcel Dalio", "Marcello Mastroianni", "Marcia Gay Harden", "Marco Giallini", 
      "Mare Winningham", "Margaret Avery", "Margaret Livingston", "Margaret Lockwood", 
      "Margaret Sullavan", "Margaret Wycherly", "Margaretha Krook", "Margarita Terekhova", 
      "Margot Robbie", "Maria Doyle Kennedy", "Maria Falconetti", "Maria Grazia Cucinotta", 
      "María Marull", "María Mercedes Villagra", "Maria Monti", "Marianne Koch", 
      "Maribel Verdú", "Marie-Josée Croze", "Marie-Laure Dougnac", "Mariel Hemingway", 
      "Marília Pêra", "Marilyn Eastman", "Marilyn Ghigliotti", "Marilyn Monroe", 
      "Marina de Tavira", "Marina Vasileva", "Mario Casas", "Marion Cotillard", "Marion Mack", 
      "Marisa Berenson", "Marisa Paredes", "Marisa Tomei", "Marius Goring", "Marjane Satrapi", 
      "Mark Boone Junior", "Mark Hamill", "Mark Margolis", "Mark Ruffalo", "Mark Rydell", 
      "Mark Rylance", "Mark Strong", "Mark Wahlberg", "Markéta Irglová", "Markus Rygaard", 
      "Marlene Dietrich", "Marlon Brando", "Marlon Wayans", "Martha Vickers", "Martin Balsam", 
      "Martin Freeman", "Martin Landau", "Martin Milner", "Martin Sheen", "Martin Stringer", 
      "Martina Gedeck", "Marty Feldman", "Mary Astor", "Mary Elizabeth Mastrantonio", 
      "Mary Kay Bergman", "Mary McDonnell", "Mary Steenburgen", "Mary Stuart Masterson", 
      "Mary Tyler Moore", "Mary Ure", "Mary-Louise Parker", "Maryana Spivak", "Masaaki Ôkura", 
      "Masahiko Nishimura", "Masahiro Motoki", "Masaki Okada", "Masayuki Mori", "Massimo Troisi", 
      "Matheus Nachtergaele", "Mathieu Amalric", "Mathieu Kassovitz", "Matt Damon", 
      "Matt Stone", "Matthew Broderick", "Matthew Edison", "Matthew Goode", "Matthew Macfadyen", 
      "Matthew McConaughey", "Matthew Modine", "Matvey Novikov", "Maureen O'Hara", 
      "Maureen O'Sullivan", "Maurice Evans", "Maurice Schutz", "Max Phipps", "Max Riemelt", 
      "Max Schreck", "Max von Sydow", "Maxim Gaudette", "Maxine Audley", "May Whitty", 
      "Mayu Matsuoka", "Mayumi Izuka", "Mayumi Tanaka", "Mckenna Grace", "Meat Loaf", 
      "Meena", "Meg Ryan", "Megs Jenkins", "Megumi Hayashibara", "Megumi Ogata", 
      "Mehdi Nebbou", "Mel Gibson", "Mélanie Laurent", "Mélanie Thierry", "Melinda Dillon", 
      "Melisa Sözen", "Melissa Benoist", "Mélissa Désormeaux-Poulin", "Melissa Leo", 
      "Melora Walters", "Melvyn Douglas", "Mercedes Morán", "Merila Zare'i", "Merna Kennedy", 
      "Mervyn LeRoy", "Meryl Streep", "Mete Horozoglu", "Mia Farrow", "Mía Maestro", 
      "Mia Sara", "Michael Ansara", "Michael B. Jordan", "Michael Bates", "Michael Beck", 
      "Michael Berryman", "Michael Biehn", "Michael Caine", "Michael Clarke Duncan", 
      "Michael Douglas", "Michael Ealy", "Michael Fassbender", "Michael Gambon", 
      "Michael J. Fox", "Michael J. Pollard", "Michael Keaton", "Michael Kenneth Williams", 
      "Michael Lee Gogin", "Michael Madsen", "Michael McKean", "Michael Murphy", 
      "Michael Nyqvist", "Michael Palin", "Michael Peña", "Michael Preston", "Michael Redgrave", 
      "Michael Rennie", "Michael Schwartz", "Michael Sheen", "Michael Strong", "Michael Stuhlbarg", 
      "Michael York", "Michel Auclair", "Michel Côté", "Michel Piccoli", "Michel Robin", 
      "Michèle Caucheteux", "Michelle Dockery", "Michelle La", "Michelle Monaghan", 
      "Michelle Pfeiffer", "Michelle Reis", "Michelle Rodriguez", "Michelle Williams", 
      "Michelle Yeoh", "Mick Lally", "Mickey Rourke", "Miguel Ángel Fuentes", "Mikael Persbrandt", 
      "Mike Myers", "Mike Vitar", "Miki Imai", "Mikkel Boe Følsgaard", "Mila Kunis", 
      "Mila Parély", "Miles Teller", "Milhem Cortaz", "Milla Jovovich", "Mina Sadati", 
      "Minami Takayama", "Ming-Na Wen", "Minori Terada", "Minoru Chiaki", "Miori Takimoto", 
      "Mirai Shida", "Miranda Richardson", "Miriam Shor", "Mirjana Jokovic", "Misa Uehara", 
      "Misha Meskhi", "Miss Piggy", "Mitchell Ryan", "Mitchell Whitfield", "Mithun Chakraborty", 
      "Mitsuo Iwata", "Mitsutaka Itakura", "Miyu Irino", "Mohammad Amir Naji", "Mohanlal", 
      "Mohit Raina", "Moira Shearer", "Molly Picon", "Molly Ringwald", "Mona Singh", 
      "Mone Kamishiraishi", "Monica Viegas", "Mónica Villa", "Monica Vitti", "Montgomery Clift", 
      "Moon So-Ri", "Morena Baccarin", "Morgan Freeman", "Moritz Bleibtreu", "Muhammet Uzuner", 
      "Mustafa Kamel", "Myrna Loy", "Nafise Jafar-Mohammadi", "Nakul Roshan Sahdev", 
      "Nanako Matsushima", "Nancy Kyes", "Nancy Olson", "Naomi Watts", "Naomie Harris", 
      "Nargis Fakhri", "Naseeruddin Shah", "Nastassja Kinski", "Nat Pendleton", "Nat Wolff", 
      "Natalie Dessay", "Natalie Portman", "Natalie Wood", "Nataliya Vdovina", "Natalya Bondarchuk", 
      "Nathalie Boltt", "Nathalie Delon", "Nathan Fillion", "Nawazuddin Siddiqui", 
      "Ned Beatty", "Neena Gupta", "Neeraj Kabi", "Neeral Mulchandani", "Neil Brown Jr.", 
      "Neil Patrick Harris", "Nell Cattrysse", "Nicholas Hoult", "Nick Frost", "Nick Moran", 
      "Nick Nolte", "Nick Offerman", "Nicolas Bro", "Nicolas Cage", "Nicole Kidman", 
      "Nicoletta Braschi", "Niels Arestrup", "Nigel Havers", "Nikolay Burlyaev", 
      "Nikolay Grinko", "Nikolay Sergeev", "Nils Poppe", "Nimrat Kaur", "Nina Petri", 
      "Nina van Pallandt", "Nisa Sofiya Aksongur", "Noah Emmerich", "Nobuo Kaneko", 
      "Noémie Merlant", "Noomi Rapace", "Nora Gregor", "Nora Twomey", "Nora-Jane Noone", 
      "Noriko Hidaka", "Norma Crane", "Norman Ferguson", "Norman Reedus", "Norman Taurog", 
      "Nozomu Sasaki", "Nurgül Yesilçay", "Nursel Köse", "O.J. Simpson", "O'Shea Jackson Jr.", 
      "Octavia Spencer", "Oka Antara", "Oksana Akinshina", "Oleg Yankovskiy", "Olga Baclanova", 
      "Olga Mironova", "Oliver Reed", "Oliver Stokowski", "Olivia Cooke", "Olivia de Havilland", 
      "Olivia Wilde", "Olivia Williams", "Omar Sharif", "Omar Sy", "Ömer Faruk Sorak", 
      "Oprah Winfrey", "Orlando Bloom", "Orson Welles", "Orto Ignatiussen", "Osamu Saka", 
      "Oscar Isaac", "Oskar Werner", "Ossie Davis", "Otto Preminger", "Otto Sander", 
      "Otto Wernicke", "Owen Wilson", "Ozan Güven", "Özge Özberk", "Pablo Rago", 
      "Paddy Considine", "Paige O'Hara", "Pamela Adlon", "Paolo Bonacelli", "Paprika Steen", 
      "Parambrata Chattopadhyay", "Paresh Rawal", "Pascal Benezech", "Pascal Greggory", 
      "Patricia Arquette", "Patricia Clarkson", "Patricia Neal", "Patrick Fugit", 
      "Patrick Horgan", "Patrick Huard", "Patrick Magee", "Patrick McGoohan", "Patrick Renna", 
      "Patrick Stewart", "Patrick Wilson", "Patrick Wymark", "Patton Oswalt", "Paul Benjamin", 
      "Paul Bettany", "Paul Dano", "Paul Frankeur", "Paul Freeman", "Paul Giamatti", 
      "Paul Henreid", "Paul Lukas", "Paul McCartney", "Paul McGann", "Paul Meurisse", 
      "Paul Muni", "Paul Newman", "Paul Raci", "Paul Reiser", "Paul Rudd", "Paul Sanchez", 
      "Paul Scofield", "Paul Winfield", "Paulette Dubost", "Paulette Goddard", "Pauline Burlet", 
      "Pavel Ponomaryov", "Pawan Malhotra", "Payman Maadi", "Penelope Allen", "Penelope Ann Miller", 
      "Penélope Cruz", "Per Ragnar", "Pernilla Allwin", "Perry Lopez", "Pete Postlethwaite", 
      "Peter Billingsley", "Peter Boyle", "Peter Brocco", "Peter Bull", "Peter Coyote", 
      "Peter Dinklage", "Peter Finch", "Peter Lorre", "Peter O'Toole", "Peter Ostrum", 
      "Peter Ramsey", "Peter Sellers", "Peter Stormare", "Peter van Eyck", "Peter Wyngarde", 
      "Phil Harris", "Phil Lord", "Philip Chan", "Philip King", "Philip Seymour Hoffman", 
      "Philippe Noiret", "Phillip Terry", "Phillipa Soo", "Phylicia Rashad", "Phyllis Logan", 
      "Pierre Barbaud", "Pierre Brasseur", "Pierre Fresnay", "Ping Lam Siu", "Piper Laurie", 
      "Polly Bergen", "Porter Hall", "Prabhas", "Prakash Belawadi", "Prateik", "Predrag 'Miki' Manojlovic", 
      "Preity Zinta", "Priscilla Lane", "Priscilla Presley", "Priya Anand", "Priyanka Chopra", 
      "Pruitt Taylor Vince", "Pupella Maggio", "Pushkar", "Qiu Yuen", "Quentin Tarantino", 
      "Quinton Aaron", "R. Lee Ermey", "Rachel Griffiths", "Rachel House", "Rachel McAdams", 
      "Rachel Shelley", "Rachel Ticotin", "Rachel Weisz", "Radha Mitchell", "Radhika Apte", 
      "Raghuvir Yadav", "Rajat Barmecha", "Rajat Kapoor", "Rajesh Abhay", "Rajesh Khanna", 
      "Rajit Kapoor", "Rajkummar Rao", "Ralph Bellamy", "Ralph Brown", "Ralph Fiennes", 
      "Ralph Macchio", "Ralph Meeker", "Ralph Richardson", "Ram Kapoor", "Ramachandra Raju", 
      "Ramesh Deo", "Rami Malek", "Ramon Bieri", "Ramya Krishnan", "Rana Daggubati", 
      "Ranbir Kapoor", "Randy Quaid", "Rani Mukerji", "Ranveer Singh", "Raoul Max Trujillo", 
      "Raphael Fejtö", "Rashida Jones", "Raveena Tandon", "Ray Liotta", "Ray Milland", 
      "Ray Sahetapy", "Ray Walston", "Raymond Massey", "Rebecca De Mornay", "Reda Kateb", 
      "Reese Witherspoon", "Regina King", "Reginald Gardiner", "Reginald VelJohnson", 
      "Rei Sakuma", "Ren Osugi", "Rena Owen", "Rene Auberjonois", "Rene Bitorajac", 
      "Rene Russo", "Renée Elise Goldsberry", "Renée Zellweger", "Reni Santoni", 
      "Rex Harrison", "Rhonda Fleming", "Rica Matsumoto", "Ricardo Darín", "Ricardo Montalban", 
      "Rich Moore", "Richa Chadha", "Richard Armitage", "Richard Attenborough", "Richard Basehart", 
      "Richard Briers", "Richard Burton", "Richard Crenna", "Richard Dormer", "Richard Dreyfuss", 
      "Richard E. Grant", "Richard Edson", "Richard Farnsworth", "Richard Gere", 
      "Richard Griffiths", "Richard Harris", "Richard Haydn", "Richard Hunt", "Richard Jenkins", 
      "Richard Masur", "Richard Rosson", "Richard Thorpe", "Richard Widmark", "Ricky Adelayitor", 
      "Ricky Nelson", "Riisa Naka", "Rima Te Wiata", "Ringo Starr", "Rita Hayworth", 
      "River Phoenix", "Riz Ahmed", "RJ Cyler", "Rob Maxey", "Rob Minkoff", "Rob Reiner", 
      "Robby Benson", "Robert Armstrong", "Robert Arthur", "Robert Cummings", "Robert De Niro", 
      "Robert Donat", "Robert Downey Jr.", "Robert Duvall", "Robert Gulaczyk", "Robert Hays", 
      "Robert Manuel", "Robert Mitchum", "Robert Morley", "Robert Patrick", "Robert Redford", 
      "Robert Rodriguez", "Robert Ryan", "Robert Sean Leonard", "Robert Shaw", "Robert Stack", 
      "Robert Strauss", "Robert Walker", "Roberta Maxwell", "Roberto Benigni", "Roberts Blossom", 
      "Robin Williams", "Robin Wright", "Rock Hudson", "Rod Steiger", "Rod Taylor", 
      "Roddy McDowall", "Rodney A. Grant", "Rodney Rothman", "Rodrigo De la Serna", 
      "Roe-ha Kim", "Rohini Hattangadi", "Roland Møller", "Rolf Lassgård", "Roman Griffin Davis", 
      "Roman Madyanov", "Roman Polanski", "Romolo Valli", "Ron Livingston", "Ronit Roy", 
      "Ronnie Del Carmen", "Ronny Cox", "Rooney Mara", "Rory Cochrane", "Rosalind Russell", 
      "Rosamund Pike", "Rosanna Arquette", "Rosario Dawson", "Rosario Flores", "Roscoe Ates", 
      "Roscoe Karns", "Rosemarie DeWitt", "Rosemary Murphy", "Roshan Seth", "Rosie Shaw", 
      "Roy Dotrice", "Roy Kinnear", "Roy Scheider", "Ruby Dee", "Rudolf Klein-Rogge", 
      "Rudy Youngblood", "Rufus", "Rufus Sewell", "Rumi Hiiragi", "Ruocheng Ying", 
      "Rupert Friend", "Rupert Graves", "Rupert Grint", "Russell Brand", "Russell Crowe", 
      "Russell Means", "Rusty Schwimmer", "Rutger Hauer", "Ruth Gordon", "Ruth Hussey", 
      "Ruth Nelson", "Ruth Roman", "Ruy Guerra", "Ryan Gosling", "Ryan Hurst", "Ryan O'Neal", 
      "Ryan Potter", "Ryan Reynolds", "Ryô Kase", "Ryô Narita", "Ryôko Hirosue", 
      "Ryûnosuke Kamiki", "Sabrina Ferilli", "Sacha Baron Cohen", "Sady Rebbot", 
      "Sae-ron Kim", "Saeed Jaffrey", "Safak Sezer", "Sagarika Ghatge", "Sahil Vaid", 
      "Saïd Taghmaoui", "Saif Ali Khan", "Saifei He", "Sakshi Tanwar", "Sakura Andô", 
      "Sal Mineo", "Salim Kechiouche", "Sally Field", "Sally Hawkins", "Sally Yeh", 
      "Salman Khan", "Sam Elliott", "Sam Jaffe", "Sam Neill", "Sam Riley", "Sam Rockwell", 
      "Sam Shepard", "Sam Waterston", "Sam Wood", "Sam Worthington", "Samantha Isler", 
      "Samantha Morton", "Samia Kerbash", "Samuel Armstrong", "Samuel E. Wright", 
      "Samuel L. Jackson", "Sandra Bernhard", "Sandra Bullock", "Sandra Milo", "Sandy Dennis", 
      "Sanjana Sanghi", "Sanjay Dutt", "Sanjeev Kumar", "Sanya Malhotra", "Saoirse Ronan", 
      "Saori Hayami", "Sara Takatsuki", "Sarah Berry", "Sarah Bolger", "Sarah Jessica Parker", 
      "Sarah Miles", "Sarah Polley", "Sarah Roemer", "Sarah Silverman", "Sarah Vowell", 
      "Sareh Bayat", "Saswata Chatterjee", "Sathyaraj", "Saurabh Shukla", "Scarlett Johansson", 
      "Scatman Crothers", "Scott Adsit", "Scott Glenn", "Scott H. Reiniger", "Scott Schwartz", 
      "Scott Weinger", "Seamus Davey-Fitzpatrick", "Sean Astin", "Sean Bean", "Sean Bridgers", 
      "Sean Connery", "Sean Patrick Flanery", "Sean Penn", "Sean Young", "Sebastian Cabot", 
      "Sebastian Koch", "Sebastian Maniscalco", "Sela Ward", "Sener Sen", "Sergi López", 
      "Sermin Hürmeriç", "Sessue Hayakawa", "Seth Rogen", "Setsuko Hara", "Seung-Yun Lee", 
      "Seymour Cassel", "Shah Rukh Khan", "Shahab Hosseini", "Shahid Kapoor", "Shailene Woodley", 
      "Shameik Moore", "Shammi Kapoor", "Sharlto Copley", "Sharman Joshi", "Sharon Percy", 
      "Sharon Stone", "Sheetal Menon", "Shelley Duvall", "Shelley Winters", "Shernaz Patel", 
      "Shigeru Muroi", "Shigesato Itoi", "Shilpa Shukla", "Shima Iwashita", "Shin Ha-kyun", 
      "Shin'ichi Himori", "Shinpachi Tsuji", "Shirley Eaton", "Shirley MacLaine", 
      "Shishir Sharma", "Shôgo Furuya", "Shraddha Kapoor", "Shraddha Srinath", "Shriya Saran", 
      "Shûichirô Moriyama", "Sibel Kekilli", "Siddharth", "Sidney Blackmer", "Sidney Poitier", 
      "Sidse Babett Knudsen", "Sienna Miller", "Sigourney Weaver", "Silvia Pinal", 
      "Simon Pegg", "Simon Yam", "Simone Signoret", "Sissy Spacek", "Siu-Lung Leung", 
      "Siu-Wong Fan", "Slavko Stimac", "Slim Pickens", "Smit Sheth", "Sô Yamamura", 
      "Soha Ali Khan", "Sohum Shah", "Soia Lira", "Soledad Villamil", "Solveig Dommartin", 
      "Sonam Kapoor", "Sondra Locke", "Song Wok-suk", "Sonia Todd", "Sonoya Mizuno", 
      "Sophie Kennedy Clark", "Sophie Marceau", "Sophie Okonedo", "Sophie Perry", 
      "Spencer Tracy", "Spike Lee", "Srdjan 'Zika' Todorovic", "Sridevi", "Srinidhi Shetty", 
      "Stanislas Carré de Malberg", "Stanley Baker", "Stanley Holloway", "Stefania Sandrelli", 
      "Stella Dassas", "Stellan Skarsgård", "Stephen Baldwin", "Stephen Boyd", "Stephen Chow", 
      "Stephen Graham", "Stephen Rea", "Stephen Tobolowsky", "Stephen Trask", "Stephen Young", 
      "Sterling Hayden", "Steve Buscemi", "Steve Carell", "Steve Coogan", "Steve Martin", 
      "Steve McQueen", "Steve Zahn", "Steven Bauer", "Strother Martin", "Stuart Wolfenden", 
      "Sully Boyar", "Sumi Shimamoto", "Sumita Sanyal", "Sunil Dutt", "Sunil Shetty", 
      "Sunny Pawar", "Suraj Sharma", "Suriya", "Susan Harrison", "Susanne Lothar", 
      "Sushant Singh Rajput", "Susumu Terajima", "Suzanne Clément", "Suzanne Pleshette", 
      "Sylvester Stallone", "Sylvia Hoeks", "Sylvia Miles", "Sylvie Testud", "T.J. Miller", 
      "Taapsee Pannu", "Tabu", "Tae-hoon Kim", "Tae-Hyun Cha", "Tahar Rahim", "Taika Waititi", 
      "Takako Matsu", "Takao Osawa", "Takashi Shimura", "Takashi Tachibana", "Takeshi Aono", 
      "Takeshi Kaneshiro", "Takeshi Kitano", "Takuya Ishida", "Takuya Kimura", "Talia Shire", 
      "Tallulah Bankhead", "Tamannaah Bhatia", "Taner Birsel", "Taraji P. Henson", 
      "Taraneh Alidoosti", "Tarô Yamamoto", "Taron Egerton", "Tarun Arora", "Tatsuya Fujiwara", 
      "Tatsuya Gashûin", "Tatsuya Nakadai", "Tatum O'Neal", "Telly Savalas", "Temuera Morrison", 
      "Tensai Okamura", "Teo Briones", "Terence Alexander", "Teresa Mo", "Teresa Palmer", 
      "Teresa Wright", "Teri Garr", "Teri Hatcher", "Terrence Howard", "Terry Gilliam", 
      "Terry Jones", "Tessa Mitchell", "Tessa Thompson", "Tesshô Genda", "Tetsurô Tanba", 
      "Thandie Newton", "Thelma Ritter", "Theodore Liscinski", "Thibault Verhaeghe", 
      "Thierry Lhermitte", "Thierry van Werveke", "Thom Hoffman", "Thomas Bo Larsen", 
      "Thomas F. Wilson", "Thomas Kretschmann", "Thomas Mann", "Thomas Mitchell", 
      "Thomas Turgoose", "Thomasin McKenzie", "Thora Birch", "Tigmanshu Dhulia", 
      "Til Schweiger", "Tilda Swinton", "Tim Allen", "Tim Blake Nelson", "Tim Holt", 
      "Tim McGraw", "Tim Robbins", "Tim Roth", "Timothée Chalamet", "Timothy Bottoms", 
      "Timothy Hutton", "Timothy Spall", "Tina Fey", "Tiny Sandford", "Tippi Hedren", 
      "Tisca Chopra", "Tobey Maguire", "Toby Kebbell", "Tokiko Katô", "Tom Berenger", 
      "Tom Cruise", "Tom Guiry", "Tom Hanks", "Tom Hardy", "Tom Helmore", "Tom Hiddleston", 
      "Tom Hulce", "Tom Murray", "Tom Prior", "Tom Sizemore", "Tom Skerritt", "Tom Waits", 
      "Tom Wilkinson", "Tommy Chong", "Tommy Lee Jones", "Tomoko Yamaguchi", "Toni Collette", 
      "Toni Servillo", "Tony Chiu-Wai Leung", "Tony Curtis", "Tony Hale", "Tony Lo Bianco", 
      "Tony Moran", "Tony Roberts", "Tony Todd", "Topol", "Tôru Emori", "Tôru Furuya", 
      "Toshirô Mifune", "Toshirô Yanagiba", "Treat Williams", "Trevor Howard", 
      "Trevor Jack Brooks", "Trey Parker", "Trine Dyrholm", "Tsunehiko Kamijô", 
      "Tsutomu Tatsumi", "Tsutomu Yamazaki", "Tsuyoshi Ihara", "Tugba Sunguroglu", 
      "Tuncel Kurtiz", "Tung Cho 'Joe' Cheung", "Tyler Hoechlin", "Tyler Perry", 
      "Tyrone Power", "Ugur Yücel", "Ulla Jacobsson", "Ulrich Matthes", "Ulrich Mühe", 
      "Ulrich Thomsen", "Ulrich Tukur", "Uma Thurman", "Val Kilmer", "Valentin Zubkov", 
      "Valeria Golino", "Valerie Faris", "Valerie Hobson", "Vanessa Redgrave", "Vanna Urbino", 
      "Varun Sharma", "Veerle Baetens", "Véra Clouzot", "Vera Miles", "Verna Bloom", 
      "Vernon Dobtcheff", "Veronica Cartwright", "Vicellous Shannon", "Vicky Jenson", 
      "Vicky Kaushal", "Victor Buono", "Victor Jory", "Victor Sjöström", "Victor Slezak", 
      "Victoria Horne", "Vidya Balan", "Vidya Malvade", "Viggo Mortensen", "Vijay Raaz", 
      "Vijay Sethupathi", "Vijay Varma", "Vin Diesel", "Vince Edwards", "Vince Vaughn", 
      "Vincent Cassel", "Vincent D'Onofrio", "Vincent Price", "Ving Rhames", "Vinícius de Oliveira", 
      "Viola Davis", "Virginia Cherrill", "Virginia Mayo", "Vivian Pickles", "Vivien Leigh", 
      "Vlad Ivanov", "Vladas Bagdonas", "Vladimir Barskiy", "Vladimir Garin", "Vladimir Vdovichenkov", 
      "Vladislav Dvorzhetskiy", "Wagner Moura", "Wah Yuen", "Wallace Ford", "Walter Brennan", 
      "Walter Catlett", "Walter Connolly", "Walter Hampden", "Walter Huston", "Walter Matthau", 
      "Walter Slezak", "Walton Goggins", "Ward Bond", "Warren Beatty", "Warren Clarke", 
      "Warren Oates", "Wendee Lee", "Wendell Corey", "Wendy Crewson", "Wendy Hiller", 
      "Werner Krauss", "Wes Bentley", "Wesley Addy", "Whoopi Goldberg", "Wil Johnson", 
      "Wil Wheaton", "Wiley Wiggins", "Wilford Brimley", "Wilfrid Hyde-White", "Will Ferrell", 
      "Will Forte", "Will Patton", "Will Poulter", "Will Smith", "Willem Dafoe", 
      "William Atherton", "William Bendix", "William Daniels", "William H. Lynn", 
      "William H. Macy", "William Harrigan", "William Hickey", "William Holden", 
      "William Hurt", "William Keighley", "William Powell", "William Sadler", "William Shatner", 
      "William Sylvester", "Winona Ryder", "Wladyslaw Kowalski", "Wolfgang Lukschy", 
      "Won Bin", "Wood Harris", "Woody Allen", "Woody Harrelson", "Wotan Wilke Möhring", 
      "Xolani Mali", "Yacef Saadi", "Yalitza Aparicio", "Yami Gautam", "Yash", "Yasuo Yamada", 
      "Yayan Ruhian", "Yeong-hie Seo", "Yeong-su Oh", "Yesim Salkim", "Yilmaz Erdogan", 
      "Yôji Matsuda", "Yoko Honna", "Yôko Tsukasa", "Yong Dong", "Yoo Ji-Tae", 
      "Yoo-Jeong Kim", "Yordanos Shiferaw", "Yoshiaki Umegaki", "Yoshiko Shinohara", 
      "Yoshino Kimura", "Yoshiyuki Takei", "You Ge", "Yû Kashii", "Yukiko Shimazaki", 
      "Yukito Nishii", "Yûko Miyamura", "Yûko Tanaka", "Yul Brynner", "Yun Qu", 
      "Yun-Fat Chow", "Yûnosuke Itô", "Yuriko Ishida", "Yutaka Sada", "Yves Montand", 
      "Yvonne Furneaux", "Zac Mattoon O'Brien", "Zach Galifianakis", "Zach Grenier", 
      "Zachary Levi", "Zachary Quinto", "Zack Gottsagen", "Zain Al Rafeea", "Zamira Saunders", 
      "Zarah Jane McKenzie", "Zazie Beetz", "Zbigniew Zamachowski", "Zeppo Marx", 
      "Ziyi Zhang", "Zoë Kravitz", "Zoe Saldana", "Zooey Deschanel"))
  app$set_inputs(star_open = FALSE, allow_no_input_binding_ = TRUE)
  app$expect_screenshot()
})


test_that("{shinytest2} recording: Morgan_movies_rating_by_genre", {
  app <- AppDriver$new(variant = platform_variant(), name = "Morgan_movies_rating_by_genre", 
      height = 914, width = 1379)
  app$set_inputs(genre_open = TRUE, allow_no_input_binding_ = TRUE)
  app$set_inputs(genre = c("Action", "Adventure", "Animation", "Biography", "Comedy", 
      "Crime", "Drama", "Family", "Fantasy", "Film-Noir", "History", "Horror", "Music", 
      "Musical", "Mystery", "Romance", "Sci-Fi", "Sport", "Thriller", "War", "Western"))
  app$set_inputs(genre_open = FALSE, allow_no_input_binding_ = TRUE)
  app$expect_screenshot()
})


test_that("{shinytest2} recording: morgan_download_tsv", {
  app <- AppDriver$new(name = "morgan_download_tsv", height = 914, width = 1379)
  app$set_inputs(genre_open = TRUE, allow_no_input_binding_ = TRUE)
  app$set_inputs(genre = c("Action", "Adventure", "Animation", "Biography", "Comedy", 
      "Crime", "Drama", "Family", "Fantasy", "Film-Noir", "History", "Horror", "Music", 
      "Musical", "Mystery", "Romance", "Sci-Fi", "Sport", "Thriller", "War", "Western"))
  app$set_inputs(genre_open = FALSE, allow_no_input_binding_ = TRUE)
  app$expect_download("download")
  app$expect_values()
})
